image: gradle:7.2.0-jdk17

stages:
  - build
  - test
#  - converage

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script:
    - gradle test # jacocoTestReport
  coverage: '/Total.*?([0-9]{1,3})%/'
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
      - build/jacocoHtml
      - build/reports
      - build/jacoco/test.exec
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

#coverage:
#  # Must be in a stage later than test's stage.
#  # The `visualize` stage does not exist by default.
#  # Please define it first, or chose an existing stage like `deploy`.
#  stage: visualize
#  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
#  script:
#    # convert report from jacoco to cobertura, using relative project path
#    - python /opt/cover2cover.py build/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > build/cobertura.xml
#  needs: ["test"]
#  artifacts:
#    reports:
#      coverage_report:
#        coverage_format: cobertura
#        path: build/cobertura.xml